title: Funky Trees Docs
description: Funky Trees Language Documentation
theme: just-the-docs
url: "https://snowflake0s.github.io/funkytrees"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: dark

# External navigation links
nav_external_links:
  - title: Contribute or Report Issues
    url: https://github.com/SnoWFLakE0s/funkytrees
    hide_icon: false
    opens_in_new_tab: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2020-2026 Joshua Eah. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/SnoWFLakE0s/funkytrees" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
